import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {makePreview} from './preview-built-room.mjs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 for(const width of [1440,390]){
  const page=await makePreview(browser,{viewport:{width,height:width===390?844:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://room.preview/',{waitUntil:'networkidle',timeout:90000});const enter=page.getByRole('button',{name:'STEP INSIDE',exact:true});await enter.waitFor({timeout:60000});await page.waitForFunction(()=>!document.querySelector('.opening-enter').disabled);await page.waitForFunction(()=>document.querySelector('video').readyState>=2);assert.equal(await page.locator('video').evaluate(v=>v.muted),true);assert.equal(await page.locator('.opening-gate').evaluate(e=>e.clientWidth===innerWidth&&e.clientHeight===innerHeight),true);assert.equal(await page.locator('video').evaluate(v=>v.paused),true);assert.equal(await page.locator('video').evaluate(v=>getComputedStyle(v).objectFit),'contain');await page.screenshot({path:`artifacts/opening-ready-${width}.png`});await enter.click();await page.waitForFunction(()=>document.querySelector('video')?.currentTime>.9);await page.screenshot({path:`artifacts/opening-door-${width}.png`});await page.waitForFunction(()=>document.querySelector('video')?.currentTime>2.5);assert.ok(Number(await page.locator('video').evaluate(v=>v.style.scale))>1);await page.screenshot({path:`artifacts/opening-zoom-${width}.png`});await page.waitForSelector('.opening-gate',{state:'detached',timeout:15000});await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.settled==='room');assert.equal(await page.locator('.room-toolbar').count(),1);await page.screenshot({path:`artifacts/opening-arrived-${width}.png`});assert.deepEqual(errors,[]);await page.close();console.log('PASS',width,'full-screen silent door, explicit entry, video playback, direct locker arrival');
 }
 const reduced=await makePreview(browser,{reducedMotion:'reduce'});await reduced.goto('http://room.preview/',{waitUntil:'networkidle',timeout:90000});await reduced.getByRole('button',{name:'STEP INSIDE',exact:true}).click({timeout:60000});await reduced.waitForSelector('.opening-gate',{state:'detached',timeout:3000});assert.equal(await reduced.locator('.room-toolbar').count(),1);await reduced.close();console.log('PASS reduced-motion direct entry');
 const fail=await makePreview(browser);await fail.route('**/opening-door-*.mp4',r=>r.fulfill({status:404,body:'Missing'}));await fail.goto('http://room.preview/',{waitUntil:'networkidle',timeout:90000});await fail.getByRole('button',{name:'STEP INSIDE',exact:true}).click({timeout:60000});await fail.waitForSelector('.opening-gate',{state:'detached',timeout:10000});assert.equal(await fail.locator('.room-toolbar').count(),1);await fail.close();console.log('PASS missing video keeps portfolio accessible');
}finally{await browser.close();}
