import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {makePreview} from './preview-built-room.mjs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{for(const width of [1440,390]){
 const page=await makePreview(browser,{viewport:{width,height:width===390?844:1000}});const errors=[],models=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/models/'))models.push(r.url());});
 await page.goto('http://room.preview/',{waitUntil:'networkidle',timeout:90000});await page.getByRole('button',{name:'STEP INSIDE'}).waitFor({timeout:60000});assert.match(await page.locator('.opening-identity').innerText(),/AKASH RAM/);await page.getByRole('button',{name:'STEP INSIDE'}).click();await page.waitForSelector('.opening-gate',{state:'detached',timeout:15000});await page.waitForFunction(()=>document.querySelector('canvas').dataset.settled==='room');
 assert.ok(!models.some(m=>m.includes('ronaldo')),'room does not load a Ronaldo model');assert.equal(await page.getByRole('button',{name:'Ball challenge',exact:true}).count(),0);await page.screenshot({path:`artifacts/ui-clubhouse-${width}.png`});
 await page.getByRole('button',{name:'Projects',exact:true}).click();assert.equal(await page.locator('.projects-content h3').textContent(),'MHOMES Resort');assert.equal(await page.locator('.project-links a').first().getAttribute('href'),'https://mhomes.co.in');for(const name of ['MHOMES Resort','Shut-The-Box','SP','PortfolioForge','Streamlit AI Chat']){await page.getByRole('button',{name:'View '+name,exact:true}).click();assert.equal(await page.locator('.projects-content h3').textContent(),name);}await page.waitForFunction(()=>document.querySelector('canvas').dataset.settled==='projects');await page.screenshot({path:`artifacts/ui-projects-${width}.png`});await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Skills',exact:true}).click();for(const name of ['4-3-3','4-4-2','3-4-3']){await page.locator('.board-formations').getByRole('button',{name,exact:true}).click();assert.equal(await page.locator('.formation-skill-grid>span').count(),20);}await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Take the tour',exact:true}).click();for(let i=0;i<4;i++){await page.waitForTimeout(1200);await page.locator('#panel-title').waitFor({state:'attached'});assert.ok((await page.locator('#panel-title').textContent()).length>0);if(i===0){assert.equal(await page.locator('.host-art').count(),0);assert.equal(await page.locator('.panel-about a').count(),0);}assert.equal(await page.locator('.room-panel .tour-controls').count(),0);const panel=await page.locator('.room-panel').boundingBox(),scene=await page.locator('.room-canvas').boundingBox(),tour=await page.locator('.tour-floating').boundingBox();assert.ok(width===390?scene.y+scene.height<=panel.y+1:scene.x+scene.width<=panel.x);assert.ok(tour.y>=0&&tour.y+tour.height<=(width===390?panel.y:1000));const nav=page.locator('.experience-header nav button[aria-current=page]');assert.equal(await nav.evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await nav.evaluate(e=>getComputedStyle(e).borderRadius),'0px');await page.screenshot({path:`artifacts/shared-stop-${i}-${width}.png`});await page.getByRole('button',{name:i===3?'Finish tour':'Next stop',exact:false}).click();}
 await page.getByRole('button',{name:'Contact',exact:true}).click();assert.equal(await page.locator('.contact-socials a').count(),3);assert.equal(await page.locator('.contact-email').getAttribute('href'),'mailto:akashram.27csa@licet.ac.in');await page.keyboard.press('Escape');
 await page.locator('.room-toolbar button').filter({hasText:'To the pitch'}).click();await page.getByRole('button',{name:'Start challenge'}).waitFor();await page.waitForFunction(()=>!document.querySelector('.arcade-start').disabled);assert.equal(await page.locator('.pitch-launch h1').textContent(),'JUGGLEGAME');await page.screenshot({path:`artifacts/ui-game-${width}.png`});assert.equal(await page.locator('.next-stop,.full-celebration').count(),0);assert.equal(await page.locator('audio').count(),0);assert.ok(!models.some(m=>m.includes('ronaldo-portugal')),'blocked celebration model is not loaded');await page.getByRole('button',{name:'Start challenge',exact:true}).click();await page.waitForFunction(()=>['countdown','playing'].includes(document.querySelector('.pitch-experience').dataset.state));await page.getByRole('button',{name:'Locker room',exact:false}).click();await page.getByRole('button',{name:'Projects',exact:true}).waitFor();

 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS',width,'clubhouse, five projects, formations, tour, unchanged contact, game rules, Siuu access blocked, juggle game remains available, no runtime errors');await page.close();
}}finally{await browser.close();}
